run_unit_tests:
  stage: test
  before_script:
    - echo "Preparing test data..."
    - chmod +x ./prepare-tests.sh
    - ./prepare-tests.sh
  script:
    - echo "Running unit tests..."
  after_script:
    - echo "Cleaning up temporary files..."
    - rm -r test-data
    - ls
