variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE/microservice/$MICRO_SERVICE_NAME  
  IMAGE_TAG: "1.0"

build_image:
  stage: build
  tags:
    - ec2
    - shell
    - remote
  before_script:
    - echo "Linux user is $USER"
    - echo "Docker registry user is $CI_REGISTRY_USER"
    - echo "Docker registry name is $CI_REGISTRY"
    - echo "Docker registry image is $CI_REGISTRY_IMAGE"
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .

push_image:
  stage: build
  needs:
    - build_image
  tags:
    - ec2
    - shell
    - remote
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker push $IMAGE_NAME:$IMAGE_TAG